name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read


jobs:
  small-linux:
    name: Small / Linux
    runs-on: ubuntu-24.04

    env:
      CC: clang-23
      CXX: clang++-23
      CLANG_TIDY_BIN: clang-tidy-23
      CLANG_FORMAT_BIN: clang-format-23

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      #      - name: Install dependencies
      #        # LLVM 23
      #        # shellcheck
      #        # glm
      #        # cmake >= 3.31

      - name: Check formatting
        run: |
          ./tools/formatter/format.sh
          git diff --exit-code

      - name: Run small tests
        run: ./tests/test_small.sh

      - name: Show test log
        if: failure()
        run: |
          if [ -f tests/result/test-small.log ]; then
            cat tests/result/test-small.log
          fi

  sanitizers-macos:
    name: ASan + UBSan / macOS
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          brew install \
            glm \
            glfw \
            vulkan-volk

      - name: Run sanitizers
        run: ./tests/test_sanitizers.sh

      - name: Show sanitizer log
        if: failure()
        run: |
          if [ -f tests/result/sanitizers.log ]; then
            cat tests/result/sanitizers.log
          fi
